version: '3.0'
services:
  web:
    build: .
    command: bundle exec rackup -o 0.0.0.0 -p 9292
    volumes:
      - .:/app
    ports:
      - "9292:9292"
    tty: true
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis
